[data_provider]
use_provider = "alpaca" # Options: "alpaca" or "ib"

[backtest]
data_source = "alpaca"  # Options: "db", "alpaca"

[alpaca]
api_key = "REDACT"
api_secret = "REDACT"
base_url = "https://paper-api.alpaca.markets"
historic_url = "https://data.alpaca.markets"
websocket_url = "wss://stream.data.alpaca.markets/v2/iex"

[ib]
host = "127.0.0.1"
port = 4002        # Use 7497 for TWS, 4002 for IB Gateway
client_id = 100
